#This Makefile created by makeMakefile.pl


all :
	$(MAKE) -f ../Makefile TOP=../.. T_A=windows-x64-static  $@

.DEFAULT: force
	$(MAKE) -f ../Makefile TOP=../.. T_A=windows-x64-static  $@

force:  ;
